project_id = "pbnkrtybgtjotopdobam"

[functions.approve-tenant]
verify_jwt = false

[functions.email-hook]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.notify-admin-registration]
verify_jwt = false

[functions.register-tenant]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.verify-vat]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.delete-tenant]
verify_jwt = false

[functions.test-smtp]
verify_jwt = false
